--if not exists(Select PKID from tblAdmin)
--Begin
--		Insert into tblAdmin(LoginID,PWD) Values('admin','vVl3H4NqDOlDQz02NKMoKQ==')
--End

--------------------------------------------------------Insert Into Timezone--------------------------------------------------------
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(1,'(UTC-12:00) International Date Line West',-720)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(2,'(UTC-11:00) Coordinated Universal Time-11',-660)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(3,'(UTC-10:00) Hawaii',-600)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(4,'(UTC-09:00) Alaska',-540)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(5,'(UTC-08:00) Baja California',-480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(6,'(UTC-08:00) Pacific Time (US & Canada)',-480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(7,'(UTC-07:00) Arizona',-420)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(8,'(UTC-07:00) Chihuahua, La Paz, Mazatlan',-420)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(9,'(UTC-07:00) Mountain Time (US & Canada)',-420)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(10,'(UTC-06:00) Central America',-360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(11,'(UTC-06:00) Central Time (US & Canada)',-360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(12,'(UTC-06:00) Guadalajara, Mexico City, Monterrey',-360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(13,'(UTC-06:00) Saskatchewan',-360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(14,'(UTC-05:00) Bogota, Lima, Quito, Rio Branco',-300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(15,'(UTC-05:00) Chetumal',-300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(16,'(UTC-05:00) Eastern Time (US & Canada)',-300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(17,'(UTC-05:00) Indiana (East)',-300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(18,'(UTC-04:30) Caracas',-270)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(19,'(UTC-04:00) Asuncion',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(20,'(UTC-04:00) Atlantic Time (Canada)',-240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(21,'(UTC-04:00) Cuiaba',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(22,'(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',-240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(23,'(UTC-03:30) Newfoundland',-210)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(24,'(UTC-03:00) Brasilia',-120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(25,'(UTC-03:00) Cayenne, Fortaleza',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(26,'(UTC-03:00) City of Buenos Aires',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(27,'(UTC-03:00) Greenland',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(28,'(UTC-03:00) Montevideo',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(29,'(UTC-03:00) Salvador',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(30,'(UTC-03:00) Santiago',-180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(31,'(UTC-02:00) Coordinated Universal Time-02',-120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(32,'(UTC-02:00) Mid-Atlantic - Old',-120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(33,'(UTC-01:00) Azores',-60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(34,'(UTC-01:00) Cabo Verde Is.',-60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(35,'(UTC) Casablanca',0)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(36,'(UTC) Coordinated Universal Time',0)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(37,'(UTC) Dublin, Edinburgh, Lisbon, London',0)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(38,'(UTC) Monrovia, Reykjavik',0)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(39,'(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(40,'(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(41,'(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(42,'(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(43,'(UTC+01:00) West Central Africa',60)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(44,'(UTC+01:00) Windhoek',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(45,'(UTC+02:00) Amman',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(46,'(UTC+02:00) Athens, Bucharest',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(47,'(UTC+02:00) Beirut',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(48,'(UTC+02:00) Cairo',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(49,'(UTC+02:00) Damascus',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(50,'(UTC+02:00) E. Europe',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(51,'(UTC+02:00) Harare, Pretoria',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(52,'(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(53,'(UTC+02:00) Istanbul',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(54,'(UTC+02:00) Jerusalem',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(55,'(UTC+02:00) Kaliningrad (RTZ 1)',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(56,'(UTC+02:00) Tripoli',120)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(57,'(UTC+03:00) Baghdad',180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(58,'(UTC+03:00) Kuwait, Riyadh',180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(59,'(UTC+03:00) Minsk',180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(60,'(UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2)',180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(61,'(UTC+03:00) Nairobi',180)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(62,'(UTC+03:30) Tehran',210)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(63,'(UTC+04:00) Abu Dhabi, Muscat',240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(64,'(UTC+04:00) Baku',240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(65,'(UTC+04:00) Izhevsk, Samara (RTZ 3)',240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(66,'(UTC+04:00) Port Louis',240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(67,'(UTC+04:00) Tbilisi',240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(68,'(UTC+04:00) Yerevan',240)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(69,'(UTC+04:30) Kabul',270)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(70,'(UTC+05:00) Ashgabat, Tashkent',300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(71,'(UTC+05:00) Ekaterinburg (RTZ 4)',300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(72,'(UTC+05:00) Islamabad, Karachi',300)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(73,'(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',330)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(74,'(UTC+05:30) Sri Jayawardenepura',330)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(75,'(UTC+05:45) Kathmandu',345)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(76,'(UTC+06:00) Astana',360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(77,'(UTC+06:00) Dhaka',360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(78,'(UTC+06:00) Novosibirsk (RTZ 5)',360)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(79,'(UTC+06:30) Yangon (Rangoon)',390)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(80,'(UTC+07:00) Bangkok, Hanoi, Jakarta',420)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(81,'(UTC+07:00) Krasnoyarsk (RTZ 6)',420)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(82,'(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(83,'(UTC+08:00) Irkutsk (RTZ 7)',480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(84,'(UTC+08:00) Kuala Lumpur, Singapore',480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(85,'(UTC+08:00) Perth',480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(86,'(UTC+08:00) Taipei',480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(87,'(UTC+08:00) Ulaanbaatar',480)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(88,'(UTC+08:30) Pyongyang',510)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(89,'(UTC+09:00) Osaka, Sapporo, Tokyo',540)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(90,'(UTC+09:00) Seoul',540)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(91,'(UTC+09:00) Yakutsk (RTZ 8)',540)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(92,'(UTC+09:30) Adelaide',630)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(93,'(UTC+09:30) Darwin',570)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(94,'(UTC+10:00) Brisbane',600)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(95,'(UTC+10:00) Canberra, Melbourne, Sydney',660)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(96,'(UTC+10:00) Guam, Port Moresby',600)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(97,'(UTC+10:00) Hobart',660)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(98,'(UTC+10:00) Magadan',600)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(99,'(UTC+10:00) Vladivostok, Magadan (RTZ 9)',600)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(100,'(UTC+11:00) Chokurdakh (RTZ 10)',660)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(101,'(UTC+11:00) Solomon Is., New Caledonia',660)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(102,'(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky (RTZ 11)',720)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(103,'(UTC+12:00) Auckland, Wellington',780)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(104,'(UTC+12:00) Coordinated Universal Time+12',720)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(105,'(UTC+12:00) Fiji',720)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(106,'(UTC+12:00) Petropavlovsk-Kamchatsky - Old',720)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(107,'(UTC+13:00) Nuku''alofa',780)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(108,'(UTC+13:00) Samoa',840)
	Insert Into tblTimeZoneMaster(PKTimeZoneID,DisplayName,OffSet) Values(109,'(UTC+14:00) Kiritimati Island',840)

		--------------------------------------------------------Insert Into Currency--------------------------------------------------------
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(1,N'₹','INR','Rupees')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(2,'$','USD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(3,'Lek','ALL','Leke')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(4,'?','AFN','Afghanis')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(5,'$','ARS','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(6,'ƒ','AWG','Guilders')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(7,'$','AUD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(8,'???','AZN','New Manats')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(9,'$','BSD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(10,'$','BBD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(11,'p.','BYR','Rubles')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(12,'€','EUR','Euro')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(13,'BZ$','BZD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(14,'$','BMD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(15,'$b','BOB','Bolivianos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(16,'KM','BAM','Convertible Marka')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(17,'P','BWP','Pula')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(18,'??','BGN','Leva')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(19,'R$','BRL','Reais')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(20,'£','GBP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(21,'$','BND','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(22,'?','KHR','Riels')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(23,'$','CAD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(24,'$','KYD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(25,'$','CLP','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(26,'¥','CNY','Yuan Renminbi')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(27,'$','COP','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(28,'¢','CRC','Colón')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(29,'kn','HRK','Kuna')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(30,'?','CUP','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(31,'Kc','CZK','Koruny')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(32,'kr','DKK','Kroner')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(33,'RD$','DOP ','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(34,'$','XCD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(35,'£','EGP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(36,'$','SVC','Colones')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(37,'£','FKP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(38,'$','FJD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(39,'¢','GHC','Cedis')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(40,'£','GIP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(41,'Q','GTQ','Quetzales')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(42,'£','GGP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(43,'$','GYD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(44,'L','HNL','Lempiras')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(45,'$','HKD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(46,'Ft','HUF','Forint')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(47,'kr','ISK','Kronur')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(48,'Rp','IDR','Rupiahs')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(49,'?','IRR','Rials')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(50,'£','IMP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(51,'?','ILS','New Shekels')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(52,'J$','JMD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(53,'¥','JPY','Yen')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(54,'£','JEP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(55,'??','KZT','Tenge')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(56,'?','KPW','Won')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(57,'?','KRW','Won')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(58,'??','KGS','Soms')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(59,'?','LAK','Kips')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(60,'Ls','LVL','Lati')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(61,'£','LBP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(62,'$','LRD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(63,'CHF','CHF','Switzerland Francs')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(64,'Lt','LTL','Litai')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(65,'???','MKD','Denars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(66,'RM','MYR','Ringgits')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(67,'?','MUR','Rupees')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(68,'$','MXN','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(69,'?','MNT','Tugriks')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(70,'MT','MZN','Meticais')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(71,'$','NAD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(72,'?','NPR','Rupees')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(73,'ƒ','ANG','Guilders')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(74,'$','NZD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(75,'C$','NIO','Cordobas')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(76,'?','NGN','Nairas')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(77,'kr','NOK','Krone')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(78,'?','OMR','Rials')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(79,'?','PKR','Rupees')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(80,'B/.','PAB','Balboa')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(81,'Gs','PYG','Guarani')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(82,'S/.','PEN','Nuevos Soles')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(83,'Php','PHP','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(84,'zl','PLN','Zlotych')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(85,'?','QAR','Rials')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(86,'lei','RON','New Lei')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(87,'???','RUB','Rubles')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(88,'£','SHP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(89,'?','SAR','Riyals')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(90,'???.','RSD','Dinars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(91,'?','SCR','Rupees')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(92,'$','SGD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(93,'$','SBD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(94,'S','SOS','Shillings')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(95,'R','ZAR','Rand')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(96,'?','LKR','Rupees')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(97,'kr','SEK','Kronor')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(98,'$','SRD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(99,'£','SYP','Pounds')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(100,'NT$','TWD','New Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(101,'?','THB','Baht')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(102,'TT$','TTD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(103,'TL','TRY','Lira')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(104,'£','TRL','Liras')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(105,'$','TVD','Dollars')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(106,'?','UAH','Hryvnia')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(107,'$U','UYU','Pesos')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(108,'??','UZS','Sums')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(109,'Bs','VEF','Bolivares Fuertes')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(110,'?','VND','Dong')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(111,'?','YER','Rials')
  Insert into tblCurrencyMaster(PKCurrencyID,Symbol,ShortName,FullName) Values(112,'Z$','ZWD','Zimbabwe Dollars')
	
	-----------------Org Type----------------------------------------------------------
	Insert Into tblOrgType(PKTypeID,OrgType) Values('C','Company')

	
	
	-----------Approve Status-----------------------------------------
	Insert Into tblStatusMaster(PKID,ApproveStatus) Values(1,'Pending')
	Insert Into tblStatusMaster(PKID,ApproveStatus) Values(2,'Approved')
	Insert Into tblStatusMaster(PKID,ApproveStatus) Values(3,'Rejected')

	-----------------------Billing Frequency------------------------
	Insert Into tblBillingFrequency(PKID,Frequency) Values(1,'Weekly')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(2,'BiWeekly')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(3,'SemiMonthly')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(4,'Monthly')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(5,'BiMonthly')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(6,'Semi-Annually')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(7,'Annually')
	Insert Into tblBillingFrequency(PKID,Frequency) Values(8,'Upon Limit')

	-----------------------Contract Type-------------------------------------------
	Insert Into tblContractType(PKID,ContractType) Values(1,'Weekly')
	Insert Into tblContractType(PKID,ContractType) Values(2,'BiWeekly')
	Insert Into tblContractType(PKID,ContractType) Values(3,'SemiMonthly')
	Insert Into tblContractType(PKID,ContractType) Values(4,'Monthly')
	Insert Into tblContractType(PKID,ContractType) Values(5,'BiMonthly')
	Insert Into tblContractType(PKID,ContractType) Values(6,'Semi-Annually')
	Insert Into tblContractType(PKID,ContractType) Values(7,'Annually')
	Insert Into tblContractType(PKID,ContractType) Values(8,'Upon Limit')

	-----------------Email Location-----------------------------
	Insert Into tblEmailMsgLocation(PKID,LocationName,IsEmail,IsMsg) Values(1,'Invoice',1,0)
	Insert Into tblEmailMsgLocation(PKID,LocationName,IsEmail,IsMsg) Values(2,'Scheduling',1,0)
	Insert Into tblEmailMsgLocation(PKID,LocationName,IsEmail,IsMsg) Values(3,'Leave Request',1,0)
	Insert Into tblEmailMsgLocation(PKID,LocationName,IsEmail,IsMsg) Values(4,'Appointment',1,0)

	--------------Payment Type-----------------------------------------------------------
	Insert Into tblPaymentType(PKID,PaymentType) Values(1,'Receipt')
	Insert Into tblPaymentType(PKID,PaymentType) Values(2,'Use Retainer')
	Insert Into tblPaymentType(PKID,PaymentType) Values(3,'Write Off')

	--------------------Payment Mode-------------------------------
	Insert Into tblPayModeMaster(PKID,PaymentMode,PayType,BStatus) Values(1,'Cash','CA',1)
	Insert Into tblPayModeMaster(PKID,PaymentMode,PayType,BStatus) Values(2,'Check','CH',1)
	Insert Into tblPayModeMaster(PKID,PaymentMode,PayType,BStatus) Values(3,'Credit Card','CC',1)
	Insert Into tblPayModeMaster(PKID,PaymentMode,PayType,BStatus) Values(4,'E-Check','EC',1)
	Insert Into tblPayModeMaster(PKID,PaymentMode,PayType,BStatus) Values(5,'Paypal','PP',1)


	--------------------Schedule Status-------------------------------------
	Insert Into tblScheduleStatus(PKID,StatusTitle) Values(1,'Pending')
	Insert Into tblScheduleStatus(PKID,StatusTitle) Values(2,'Confirmed by the Client')
	Insert Into tblScheduleStatus(PKID,StatusTitle) Values(3,'Canceled')

	----------------Week Days---------------------------------

	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(1,'Sunday','SUN')
	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(2,'Monday','MON')
	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(3,'Tuesday','TUE')
	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(4,'Wednesday','WED')
	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(5,'Thursday','THU')
	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(6,'Friday','FRI')
	Insert Into tblWeekDays(PKID,WDayName,ShortName) Values(7,'Saturday','SAT')


	-----------------------Asset Location-------------------------
	Insert Into tblLocationMaster(PKID,LocationName) Values(1,'Individual')
	Insert Into tblLocationMaster(PKID,LocationName) Values(2,'Department')
	Insert Into tblLocationMaster(PKID,LocationName) Values(3,'Store')
	Insert Into tblLocationMaster(PKID,LocationName) Values(4,'Repair')

	-------------Asset Condition----------------
	Insert Into tblAssetConditionMaster(PKID,Condition) Values(1,'New')
	Insert Into tblAssetConditionMaster(PKID,Condition) Values(2,'Good')
	Insert Into tblAssetConditionMaster(PKID,Condition) Values(3,'Fair')
	Insert Into tblAssetConditionMaster(PKID,Condition) Values(4,'Average')
	Insert Into tblAssetConditionMaster(PKID,Condition) Values(5,'Poor')