CREATE TABLE [dbo].[tblCompany]
(
	PKCompanyID			Bigint Not Null,
	CompanyID			Varchar(50),
	CompanyName			Varchar(50),
	Address1			Varchar(200),
	Address2			Varchar(200),	
	FKTahsilID			Bigint,	
	FKCityID			Bigint,
	FKStateID			Bigint,
	FKCountryID			Bigint,
	ZIP					Varchar(10),
	Mobile				Varchar(15),
	Phone				Varchar(15),
	Email				Varchar(50),
	Fax					Varchar(50),
	CPerson				Varchar(50),
	CPersonTitle		Varchar(50),
	GSTNo				Varchar(20),
	PANNo				Varchar(20),
	LogoURL				Varchar(50),
	SmallLogoURL		Varchar(50),
	Website				Varchar(200),
	SystemURL			Varchar(200),
	RegDate				Date,	
	FKTimezoneID		Bigint,
	FKCurrencyID		Bigint,
	CurrencySymbol		NVarchar(5),
	DateForStr			Varchar(50),
	AdminURL			Varchar(200),
	InvoicePrefix       VARCHAR (50) default '',
    InvoiceSuffix       VARCHAR (50) default '',
    InvoiceSNo          BIGINT default 1 ,
	InvoiceTempID	    Int default 1 ,
	AttenUserName		Varchar(50),
	AttenPWD			Varchar(50),
	CreationDate		DateTime,
	ModificationDate	DateTime
)
