CREATE TABLE [dbo].[tblClient]
(
	PKID                BIGINT        NOT NULL,
    FKCompanyID         Bigint        Not NULL,
    FKManagerID         Bigint        NULL,  
    Code                VARCHAR (50)  NULL,
    Company             VARCHAR (200) NULL,
    CPerson				Varchar(50),
	CPersonTitle		Varchar(50),
    ActiveStatus        VARCHAR (50)  NULL Default 'Active',
    Address1			Varchar(200),
	Address2			Varchar(200),
	FKTahsilID			Bigint,	
	FKCityID			Bigint,
	FKStateID			Bigint, 
	FKCountryID		    Bigint,
	ZIP				    Varchar(10),
    EMailID             VARCHAR (50)  NULL,
    Phone1			    Varchar(15),
	Phone2			    Varchar(15),
    Mobile              VARCHAR (50)  NULL,
    Fax                 VARCHAR (50)  NULL,
    Website             VARCHAR (500) NULL,
    PWD                 VARCHAR (50)  NULL, 
    TotalDr             Decimal(18,4) Default 0,
    TotalCr             Decimal(18,4) Default 0,
    Balance             AS (TotalDr-TotalCr), 
    Retainer            Decimal(18,4) Default 0,
    BStatus             BIT  Default 1,     
    FKCreatedBy			Bigint,	
	FKLastModifiedBy	Bigint,	
	CreationDate		DateTime	Not Null,
	ModificationDate	DateTime		
)
