CREATE TABLE [dbo].[tblExpensesLog]
(
	 PKID                   BIGINT          NOT NULL,
     TaskDate               Date            Not NULL,
     FKTaskID               Bigint,
     FKEmpID                Bigint, 
     FKProjectID            Bigint, 
     Unit                   DECIMAL (18, 4),
     Description            NVARCHAR (2000),  
     IsBillable             BIT,  
     Memo                   NVARCHAR (4000) ,
     TCostRate              DECIMAL (18, 4),
     MU                     DECIMAL (18, 4),
     Amount                 DECIMAL (18, 4),   
     IsReimb                 BIT ,    
     SavedFileName          Varchar(max),
     OriginalFileName        Varchar(max),
     ApproveStatus          Varchar(50) Default 'Pending',
     FKApproveByID          Bigint, 
     ApproveDate            DateTime,
     ApproveRemark          NVarchar(2000),
     IsBilled               Bit Default 0,
     FKInvoiceID            Bigint,
     FKCompanyID		    Bigint, 
     FKCreatedBy		    Bigint,	
	 FKLastModifiedBy       Bigint,	
	 CreationDate	        DateTime,
	 ModificationDate       DateTime,		
     BStatus                BIT   Default 1
)
