CREATE TABLE [dbo].[tblInvoice]
(
	PKID				Bigint Not Null,
	InvDate				Date,
	FKProjectID			Bigint, 
	SNo					Bigint,
	ProjectSNo			Bigint,
	Prefix				VARCHAR (50),
    Suffix				VARCHAR (50),
	InvoiceID			Varchar(200),	
	CPerson				Varchar(50),
	CPersonTitle		Varchar(50),
	Address1			Varchar(200),
	Address2			Varchar(200),
	FKTahsilID			Bigint,	
	FKCityID			Bigint,
	FKStateID			Bigint, 
	FKCountryID		    Bigint,
	ZIP				    Varchar(10),
	SubAmt				Decimal(18,4),
	FKTaxID				Bigint, 
	TaxPer 				Decimal(18,4),
	TaxAmt				Decimal(18,4),
	Amount				Decimal(18,4),
	Discount			Decimal(18,4),
	NetAmount			Decimal(18,4),
	Retainage			Decimal(18,4),
	DueAmount			As (NetAmount-Retainage),
	RecAmount			Decimal(18,4) Default 0,
	WriteOff			Decimal(18,4) Default 0,
	NetDueAmount		As ((NetAmount)-(Retainage+RecAmount+WriteOff)),
	FKPayTermID			Bigint, 
	PaymentTerm			NVarchar(2000),
	Remarks				NVarchar(2000),
	IsCancel			Bit Default 0,
	CancelReason		NVarchar(2000),
	FKCurrencyID		Bigint, 
	FKCompanyID			Bigint,
	FKCreatedBy			Bigint,	
	IsDeleted			Bigint, --Added by nilesh to show Trash Invoices
	IsArchieved			Bigint, --Added by Nilesh to old archieved invoices
	
	FKLastModifiedBy	Bigint,	
	CreationDate		DateTime	Not Null,
	ModificationDate	DateTime,
	FKSubmitToId		Bigint,
	ApprovedStatus		varchar(50),
	FkApprovedById		Bigint,
	ApprovedDate		DateTime,
	ApprovedRemark		nvarchar(2000)
)
