CREATE TABLE [dbo].[tblUser]
(
	PKUserID			Bigint		    Not Null,
	LoginID				Varchar(50)	    Not Null,
	SNo					Bigint,
	EmailID				Varchar(50)	    Not Null,
	PWD					Varchar(200)	Not Null,
	FName				Varchar(50)	    Not Null,
	MName				Varchar(50)	,
	LName				Varchar(50),
	EnrollNo			Varchar(50)	, 
	DOB					Date,
	Gender				Varchar(50),
	MobNo				Varchar(15),	
	Phone1				Varchar(15),
	Phone2				Varchar(15),
	AddressTitle		Varchar(200),
	Address1			Varchar(200),
	Address2			Varchar(200),
	FKTahsilID			Bigint,	
	FKCityID			Bigint,
	FKStateID			Bigint, 
	FKCountryID			Bigint,
	ZIP					Varchar(10),
	JoinDate			Date,
	ReleasedDate		Date,
	FKManagerID			Bigint,
	FKSubmitToID		Bigint,
	OrgTypeID			Varchar(2)	Not Null,
	RoleType			Varchar(20)	Not Null,
	FKRoleGroupID		Bigint,	
	FKCompanyID			Bigint,
	FKDeptID			Bigint,	
	FKDesigID			Bigint,	
	FKTimezoneID		Bigint, 
	Remark			   NVarchar(500),
	IsAppointment	   Bit Default 0,	
	IsDefaultUser		Bit Default 0,		
	PhotoURL			Varchar(50),	
	FKDashboardID		Bigint,
	ActiveStatus		Varchar(50)	Not Null Default 'Active',	
	FKCreatedBy			Bigint,	
	FKLastModifiedBy	Bigint,	
	CreationDate		DateTime	Not Null,
	ModificationDate	DateTime,		
	UserToken			Varchar(50),	
	LastLoginDate		DateTime,
	BStatus				Bit	Not Null Default 1 
)
